language: java
jdk:
  - oraclejdk8
  
before_script:
  - "export DISPLAY=:99.0"
  
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
notifications:
  email:
    on_success: never
    on_failure: never
  slack: sapphirerain:jvrvlwIxDxTQz79CMcvXlehd